# Generated by Django 3.0.3 on 2020-07-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='product_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='your_email',
        ),
    ]
